image:
  tag: "dev"

env:
  databaseUri: "postgresql://movie_db_username:movie_db_password@movie-db:5432/movie_db_dev"
  castServiceUrl: "http://cast-service:8000/api/v1/casts/"

postgres:
  database: movie_db_dev

replicaCount: 1
